platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

project '../swift-commons/SwiftCommons.xcodeproj'
workspace '../swift-commons/SwiftCommons.xcworkspace'

target 'SwiftCommonsTests' do
  pod 'SwiftCommons', path: '../../'

  # External dependencies
  pod 'SwiftyJSON', '~> 2.4'
end
