source 'https://github.com/roxiemobile/shared-cocoa-frameworks.ios.git'

platform :ios, '8.0'
use_frameworks!

workspace '../RoxieMobile.SwiftCommons/SwiftCommons.xcworkspace'


def inject_shared_dependencies
  pod 'CryptoSwift/Static', '~> 0.8.0'
end


target 'SwiftCommons.Core.Abstractions' do
  project '../RoxieMobile.SwiftCommons/Core.Abstractions/SwiftCommons.Core.Abstractions.xcodeproj'

  target 'SwiftCommons.Core.Abstractions.UnitTests' do
    inherit! :search_paths
  end
end


target 'SwiftCommons.Core.Concurrent' do
  project '../RoxieMobile.SwiftCommons/Core.Concurrent/SwiftCommons.Core.Concurrent.xcodeproj'

  pod 'Dispatch/Static', '~> 2.0.4'

  target 'SwiftCommons.Core.Concurrent.UnitTests' do
    inherit! :search_paths
  end
end


target 'SwiftCommons.Core.Data' do
  project '../RoxieMobile.SwiftCommons/Core.Data/SwiftCommons.Core.Data.xcodeproj'

  inject_shared_dependencies
  pod 'SwiftCommons/Core/Diagnostics', path: '../../'

  target 'SwiftCommons.Core.Data.UnitTests' do
    inherit! :search_paths
  end
end


target 'SwiftCommons.Core.Diagnostics' do
  project '../RoxieMobile.SwiftCommons/Core.Diagnostics/SwiftCommons.Core.Diagnostics.xcodeproj'

  pod 'SwiftCommons/Core/Concurrent', path: '../../'
  pod 'SwiftCommons/Core/Extensions', path: '../../'

  target 'SwiftCommons.Core.Diagnostics.UnitTests' do
    inherit! :search_paths

    pod 'SwiftCommons/Core/Data', path: '../../'
  end
end


target 'SwiftCommons.Core.Extensions' do
  project '../RoxieMobile.SwiftCommons/Core.Extensions/SwiftCommons.Core.Extensions.xcodeproj'

  pod 'SwiftCommons/Core/Abstractions', path: '../../'
  pod 'SwiftCommons/Core/Logging', path: '../../'

  target 'SwiftCommons.Core.Extensions.UnitTests' do
    inherit! :search_paths
  end
end


target 'SwiftCommons.Core.Lang' do
  project '../RoxieMobile.SwiftCommons/Core.Lang/SwiftCommons.Core.Lang.xcodeproj'

  target 'SwiftCommons.Core.Lang.UnitTests' do
    inherit! :search_paths
  end
end


target 'SwiftCommons.Core.Logging' do
  project '../RoxieMobile.SwiftCommons/Core.Logging/SwiftCommons.Core.Logging.xcodeproj'

  pod 'SwiftCommons/Core/Concurrent', path: '../../'
  pod 'SwiftCommons/Core/Lang', path: '../../'

  target 'SwiftCommons.Core.Logging.UnitTests' do
    inherit! :search_paths
  end
end


target 'SwiftCommons.Infrastructure.Database' do
  project '../RoxieMobile.SwiftCommons/Infrastructure.Database/SwiftCommons.Infrastructure.Database.xcodeproj'

  inject_shared_dependencies
  pod 'SwiftCommons/Core/Concurrent', path: '../../'
  pod 'SwiftCommons/Core/Extensions', path: '../../'
  pod 'SQLite.swift/SQLCipher/Static', '~> 0.11.4'

  target 'SwiftCommons.Infrastructure.Database.UnitTests' do
    inherit! :search_paths
  end
end
