platform :ios, '8.0'
use_frameworks!

workspace '../RoxieMobile.SwiftCommons/SwiftCommons.xcworkspace'

target 'SwiftCommons.Core.Diagnostics' do
  project '../RoxieMobile.SwiftCommons/Core.Diagnostics/SwiftCommons.Core.Diagnostics.xcodeproj'

  pod 'SwiftCommons/Core/Lang', :path => '../../'

  target 'SwiftCommons.Core.Diagnostics.UnitTests' do
    inherit! :search_paths
  end
end

target 'SwiftCommons.Core.Extensions' do
  project '../RoxieMobile.SwiftCommons/Core.Extensions/SwiftCommons.Core.Extensions.xcodeproj'

  pod 'SwiftCommons/Core/Lang', :path => '../../'
  pod 'SwiftCommons/Core/Logging', :path => '../../'

  target 'SwiftCommons.Core.Extensions.UnitTests' do
    inherit! :search_paths
  end
end

target 'SwiftCommons.Core.Logging' do
  project '../RoxieMobile.SwiftCommons/Core.Logging/SwiftCommons.Core.Logging.xcodeproj'

  pod 'SwiftCommons/Core/Concurrent', :path => '../../'
  pod 'SwiftCommons/Core/Lang', :path => '../../'

  target 'SwiftCommons.Core.Logging.UnitTests' do
    inherit! :search_paths
  end
end

target 'SwiftCommons.Infrastructure.Database' do
  project '../RoxieMobile.SwiftCommons/Infrastructure.Database/SwiftCommons.Infrastructure.Database.xcodeproj'

  pod 'SwiftCommons/Core/Concurrent', :path => '../../'
  pod 'SwiftCommons/Core/Extensions', :path => '../../'
  pod 'SwiftCommons/Core/Lang', :path => '../../'
  pod 'SwiftCommons/Core/Logging', :path => '../../'
  pod 'CryptoSwift', '~> 0.7'
  pod 'SQLCipher', '~> 3.4', :inhibit_warnings => true

  target 'SwiftCommons.Infrastructure.Database.UnitTests' do
    inherit! :search_paths
  end
end

# FIXME: Must be deleted!
target 'SwiftCommons.Core.Deprecated' do
  project '../RoxieMobile.SwiftCommons/Core.Deprecated/SwiftCommons.Core.Deprecated.xcodeproj'

  pod 'SwiftCommons/Core/Concurrent', :path => '../../'
  pod 'SwiftCommons/Core/Lang', :path => '../../'
  pod 'SwiftCommons/Core/Logging', :path => '../../'
  pod 'CryptoSwift', '~> 0.7'

  target 'SwiftCommons.Core.Deprecated.UnitTests' do
    inherit! :search_paths
  end
end

# Implicit declaration of function 'sqlite3_rekey' is invalid in C99
# @link https://stackoverflow.com/a/46323483
# @link https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27

post_install do | installer |
  puts "SQLCipher: link Pods/SQLCipher/sqlite3.h"
  system "mkdir -p Pods/Headers/Private/SQLCipher && ln -s ../../../SQLCipher/sqlite3.h Pods/Headers/Private/SQLCipher"
end
