platform :ios, '8.0'
use_frameworks!

workspace '../RoxieMobile.SwiftCommons/SwiftCommons.xcworkspace'

# target 'SwiftCommons.Lang' do
#   project '../RoxieMobile.SwiftCommons/SwiftCommons.Lang/SwiftCommons.Lang.xcodeproj'
# end

target 'SwiftCommons.Deprecated' do
  project '../RoxieMobile.SwiftCommons/SwiftCommons.Deprecated/SwiftCommons.Deprecated.xcodeproj'

  pod 'SwiftCommons/Lang', :path => '../../'
  pod 'SQLCipher', '~> 3.4', :inhibit_warnings => true
end

# Implicit declaration of function 'sqlite3_rekey' is invalid in C99
# @link https://stackoverflow.com/a/46323483
# @link https://discuss.zetetic.net/t/ios-11-xcode-issue-implicit-declaration-of-function-sqlite3-key-is-invalid-in-c99/2198/27

post_install do | installer |
  puts "SQLCipher: link Pods/SQLCipher/sqlite3.h"
  system "mkdir -p Pods/Headers/Private/SQLCipher && ln -s ../../../SQLCipher/sqlite3.h Pods/Headers/Private/SQLCipher"
end
