platform :ios, '8.0'
# use_frameworks!

workspace '../RoxieMobile.SwiftCommons/SwiftCommons.xcworkspace'

target 'SwiftCommons.Deprecated' do
  project '../RoxieMobile.SwiftCommons/SwiftCommons.Deprecated/SwiftCommons.Deprecated.xcodeproj'

  pod 'SQLCipher', '~> 3.4', :inhibit_warnings => true
end
