excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - /Dependencies

disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - file_length
  - for_where
  - function_body_length
  - identifier_name
  - line_length
  - nesting
  - todo
  - type_body_length
  - type_name
  - large_tuple
  - function_parameter_count
  - notification_center_detachment

opt_in_rules: 
  - conditional_returns_on_newline
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - last_where
  - legacy_random
  - number_separator
  - private_action
  - private_outlet
  - sorted_first_last
  - sorted_imports
  - toggle_bool
  - type_contents_order
  - unused_import
  - unused_private_declaration
  - vertical_whitespace_between_cases
  - void_return
  - yoda_condition

empty_count:
    severity: warning

number_separator:
    minimum_length: 5